template-file-path: iam-resources.yml
parameters:
  S3UserEmail: s3user@gmail.com
  LambdaS3Key: iam-user-event-lambda-1.0-SNAPSHOT.jar
  LambdaS3Bucket: amalitech-bucket
  EC2UserEmail: ec2user@gmail.com
  TemporaryPassword: '****'
tags: {}
